### ISSUE TITLE
Display Score and High Score on Game Over Screen

### ISSUE THREAD

**Issue by bodhisha** [amalaabraham/flappybug#44]
Hey, Just got to see the score and high score is not displayed when the game gets over. I feel it would be cool if we include them also in the game so that the player gets a feeling to beat the score every next time.

If this sounds good, please assign it to me, I'll work on the PR and get back soon.. 

@amalaabraham @benyam7 @Nuage21

**Comment by amalaabraham** [comment]
Exactly! Thank you for trying out our game and looking forward to see the score on screen. @bodhisha assigning this to you :)
